src/main/webapp/WEB-INF/tags/boardSideBar.tag, src/main/webapp/WEB-INF/tags/header.tag, src/main/webapp/WEB-INF/tags/simpleStoreData.tag, src/main/webapp/addressSearchStore.jsp, src/main/webapp/resources/assets/css/searchvalue.css, src/main/webapp/resources/assets/css/store.css, src/main/webapp/resources/assets/js/copy.js, src/main/webapp/resources/assets/js/map/geolocation.js, src/main/webapp/resources/assets/js/map/printMap.js, src/main/webapp/resources/assets/js/storeList.js, src/main/webapp/store.jsp, src/main/webapp/storeList.jsp
jsp : store.jsp, storeList.jsp, AddressSearchStore.jsp
css : store.css, searchValue.css
tag : head.tag, boardSidebar.tag, categoryKeyword.tag, simpleStoreData.tag
js : copy.js, storeList.js, pringMap.js, geolocation.js
=> 241023 정재희 view store파트 변경

src/main/webapp/WEB-INF/tags/header.tag, src/main/webapp/WEB-INF/views/pointRecharge.jsp, src/main/webapp/WEB-INF/views/productCart.jsp, src/main/webapp/WEB-INF/views/productDetail.jsp, src/main/webapp/WEB-INF/views/productFilterList.jsp, src/main/webapp/WEB-INF/views/productList.jsp, src/main/webapp/resources/assets/css/header.css, src/main/webapp/resources/assets/css/pointRecharge.css, src/main/webapp/resources/assets/css/productCart.css, src/main/webapp/resources/assets/js/point/pointRecharge.js, src/main/webapp/resources/assets/js/product/productCart.js, src/main/webapp/resources/assets/js/product/productDetail.js, src/main/webapp/resources/assets/js/product/productList.js
1. 헤더 / 헤더 CSS
- 글씨체 변경
- 애니메이션 효과 추가
2. productList.jsp /productFilter.jsp 관련 JS CSS
- 설계에 따른 액션 데이터 값 변경 
- 카테고리 동적으로 controller에서 받는 값으로 변경
3. prdocutCart.jsp 관련 JS CSS
-  장바구니 세션을 통한 구현
-  장바구니 삭제 / 전체삭제 / 담기 기능 확인 완료
-  구매 요청 스위트 알람 ( 로그인 여부 , 결제 가능 금액 여부, 결제)
=> 안제호 - 상품 , 장바구니 ,헤더 

src/main/webapp/login.jsp, src/main/webapp/resources/assets/css/loginAndSign.css, src/main/webapp/resources/assets/js/LoginAndsign.css, src/main/webapp/resources/assets/js/loginPwFind.js, src/main/webapp/resources/assets/js/resetPw.js, src/main/webapp/signOut.jsp
* 로그인 파트 2차 구현
- 이중모달창 제작 완료.
(1차 : 회원정보 확인 / 2차 : 비밀번호 변경)
- 링크 이동 구현 완료
- 메일 API 기존 구현 데이터 가져옴(id값 중프와 동일하게 구성함)
(다른 페이지 먼저 제작 후 api구현 예정)
=> 고미진 로그인 및 회원탈퇴 파트 구현

src/main/webapp/WEB-INF/tags/categoryKeyword.tag, src/main/webapp/WEB-INF/tags/searchbar.tag, src/main/webapp/WEB-INF/tags/store/simpleStoreData.tag, src/main/webapp/WEB-INF/views/addressSearchStore.jsp, src/main/webapp/WEB-INF/views/store.jsp, src/main/webapp/WEB-INF/views/storeList.jsp, src/main/webapp/resources/assets/css/searchvalue.css, src/main/webapp/resources/assets/css/storeRegister.css, src/main/webapp/resources/assets/js/map/printMap.js, src/main/webapp/resources/assets/js/store/addressSearch.js, src/main/webapp/resources/assets/js/store/storeList.js
addressSearchStore.jsp
- 요소에 맞게 스크롤 움직이기 추가
printMap.js, addressSearch.js
- 마커와 가게 데이터의 연결을 위해 positions 배열에 가게 객체를 추가로 넣음
* searchStore(address) 수정
- 맵 범위 재생성하는 코드 수정, 검색버전에 맞게 추가
* mapBounds(map, positions, myAddress) 수정
* searchMapBounds(map, positions) 추가
- 마커 혹은 가게 데이터에 마우스를 가져갈 시 서로에 표시하는 코드 추가(js)
* showMarkerNameToDiv(marker, map, i, positions, search) : 마커에 마우스를 가져다대면 위에 가게 이름 띄우고, storeName 클래스의 div를 표시하는 함수
* showDivToMarkerName(map, positions, markers, search) : div에 마우스를 가져다 댔을 때 마커에도 오버레이가 표시되는 함수
- 확인이 끝난 후 코드 정리
* searchStore(address), myPlaceStore(address)를 searchstore 함수로 합침
* createMapAndMarker(positions)
searchvalue.css
- select 요소 글자 크기 키움
storeList.jsp
- 검색 결과 없을 때 지도, 가게 리스트 컨테이너를 합쳐서 검색 결과 없음으로 출력
- 태그 출력, 비교 값을 value 속성에서 data-role 속성으로 변경
- Controller에서 받아온 리스트 …
=> 24.10.29 정재희 view파트 store.jsp, storeList.jsp 수정

src/main/webapp/WEB-INF/tags/adminSidebar.tag, src/main/webapp/adminMainProduct.jsp, src/main/webapp/storeDeclareList.jsp
관리자 파트 미구현 데이터 제작 완료함.
1. 관리자 가게 등록 제보 목록
2. 관리자 폐점 등록 제보 목록
3. 관리자 주문내역 확인 목록
=> 10/30 14시 고미진 관리자파트(가게등록제외) 제작

src/main/java/com/bungeobbang/app/view/memberController/PageActionController.java
<Controller>
pageActionController에서 요청방식 변경 및 Controller 어노테이션 추가
=> 2024-10-31 정재준

src/main/webapp/login.jsp
login.jsp 페이지에서 변수명 안 맞던 것만 수정했습니다
=> 2024-10-31 정재준 loginjsp 변수명 수정

src/main/java/com/bungeobbang/app/biz/filterSearch/StoreFilter.java, src/main/java/com/bungeobbang/app/biz/member/MemberDAO.java, src/main/java/com/bungeobbang/app/biz/payment/PaymentServiceImpl.java, src/main/java/com/bungeobbang/app/biz/point/PointServiceImpl.java, src/main/java/com/bungeobbang/app/view/memberController/AddMemberAsyncController.java, src/main/java/com/bungeobbang/app/view/memberController/EmailAPIAsyncController.java, src/main/java/com/bungeobbang/app/view/memberController/LoginController.java, src/main/java/com/bungeobbang/app/view/memberController/MemberAsyncController.java, src/main/java/com/bungeobbang/app/view/memberController/PageActionController.java, src/main/webapp/META-INF/MANIFEST.MF, src/main/webapp/login.jsp, src/main/webapp/resources/assets/js/signUp.js, src/main/webapp/signUp.jsp
=> 241031 한지윤 로그인 회원가입 위주 수정 (미완성)

src/main/webapp/resources/assets/js/store/storeList.js
storeList.js
- 페이지 처음 로드 됐을 때도 체크 된 값 판단해서 태그를 만드는 코드 작성
=> 2024.10.31 정재희 view파트 storeList.js 코드 추가

src/main/resources/application.properties, src/main/resources/applicationContext.xml, src/main/webapp/resources/assets/js/signUp.js, src/main/webapp/signUp.jsp
<signUp.jsp>
multipart/form-data 속성 추가
이미지 업로드와 미리보기 기능의 JavaScript 함수 이름 변경
이메일 중복 확인 버튼과 인증번호 발송 버튼의 ID 변경
비밀번호 확인 기능을 위한 추가적인 HTML 요소
비밀번호 정규화 처리
이름과 닉네임 필드 ID 에러 핸들링
Bootstrap 및 Font Awesome 스타일 추가
전화번호 필드 변경 (선택)
<signUp.js>
이메일 중복 확인 및 인증번호 전송 과정 - checkEmailFunction과 sendEmail 함수에서 서버 응답의 타입을 boolean으로 처리
비밀번호 일치 및 정규식 검사 -비밀번호 정규식을 추가
비밀번호 보기 기능이 추가
닉네임 중복 확인 기능 - formatPhoneNumber 함수를 사용해 자동으로 xxx-xxxx-xxxx 형식
회원가입 버튼 클릭 시 모든 인증 확인
<application.context.xml 이메일 api 의존성 추가>
<application.properties 아이디 비번>
=> 회원가입 JSP 파일/ signup.js / application.context.xml 의존성 추가

src/main/webapp/WEB-INF/tags/footer.tag, src/main/webapp/WEB-INF/tags/header.tag, src/main/webapp/WEB-INF/views/addressSearchStore.jsp, src/main/webapp/WEB-INF/views/adminStoreRegister.jsp, src/main/webapp/WEB-INF/views/main.jsp, src/main/webapp/WEB-INF/views/store.jsp, src/main/webapp/WEB-INF/views/storeList.jsp, src/main/webapp/WEB-INF/views/storeReport.jsp, src/main/webapp/resources/assets/css/color.css, src/main/webapp/resources/assets/css/footer.css, src/main/webapp/resources/assets/css/header.css, src/main/webapp/resources/assets/css/main.css, src/main/webapp/resources/assets/css/mainPage.css, src/main/webapp/resources/assets/css/mainPageSection2.css, src/main/webapp/resources/assets/css/pagination.css, src/main/webapp/resources/assets/css/searchbar.css, src/main/webapp/resources/assets/css/store/searchvalue.css, src/main/webapp/resources/assets/css/store/store.css, src/main/webapp/resources/assets/css/store/storeRegister.css, src/main/webapp/resources/assets/css/store/storeReport.css, src/main/webapp/resources/assets/js/map/imageMap.js, src/main/webapp/resources/assets/js/map/mainMap.js
2024.10.31
가게 등록 : adminStoreRegister.jsp
가게 제보 : storeReprot.jsp
storeListjsp, store.jsp, addressSearch.jsp
스윗알랏 스크립트 가져오는 코드 추가
printMap.js
Controller에서 받아오는 값을 불러오는 변수명 DTO의 변수명과 일치시킴
adminStoreRegister.jsp
관리자의 가게 등록 페이지 기능 완성
storeDeclared 값이 N
주소 api 작성
작성란 중 하나라도 작성되지 않으면 submit 불가하게 코드 작성 (전화번호 제외)
storeReport.jsp
관리자와 유사한 기능
storeDeclared 값이 N
나머지 기능은 똑같음(같은 js사용)
storeRegister.js
가게 등록에 필요한 유효성 검사 및 기능 작성
영업시간
checked된 요일 외의 영업시간 작성란은 막음
영업 종료 시간이 영업 시작 시간보다 빠른 것을 막음
메뉴, 결제방법
checked가 되지 않아도 N 값을 넘길 수 있도록 hidden input 요소를 삭제하고 추가하는 코드 작성 submit 전 확인작업
Controller에 데이터를 넘기기 전에 빈 input 요소가 없는지 확인하는 코드
storeRegister.css
session의 margin 값 조절
import 클래스 css 추가
menuTable 클래스의 td css 추가
daumPostCode.js
함수의 이벤트 부분 수정
address.json
select에 사용할 주소 리스트
2023.11.01
mainMap.js
지도 div의 크기가 변경되면 …
=> 2024.11.01 정재희 view 파트 css 및 코드 수정, 추가

src/main/webapp/WEB-INF/views/fixBoard.jsp, src/main/webapp/resources/assets/js/board/boardFix.js
1. Ckeditor update 로직 
2. fixboard.jsp에 boarderFolder 변수로 js로 가져와서 upload 구현
3. 업로드 게시글 사진 삭제 <확인>
4. 업로드 게시글에 추가 사진 업로드 <확인>
=> 20241104 안제호 fixboard.jsp / fixboard.js #107

src/main/java/com/bungeobbang/app/biz/board/BoardDAO.java, src/main/java/com/bungeobbang/app/view/boardController/BoardController.java, src/main/webapp/WEB-INF/views/myBoardList.jsp
boad태그 jsp 파일로 이전
boardDAO 내 게시물목록 조회 제작
boardController 제작중
=> 11/5 15:00 고미진 myBoardList 종단 추가

src/main/java/com/bungeobbang/app/view/memberController/MemberController.java, src/main/java/com/bungeobbang/app/view/paymentController/PaymentController.java, src/main/webapp/WEB-INF/views/pointRecharge.jsp, src/main/webapp/resources/assets/js/point/pointRecharge.js, src/main/webapp/resources/assets/js/point/portOne.js
MemberController에 있던 /addPoint.do 요청 PaymentController 로직 이동
PaymentController에서 memberName 받아서 PointRecharge.jsp로 보내줌 (이니시스 가상계좌 결제에 사용)
PointRecharge,jsp에서 memberName 받아서 변수로 지정 후 pointRecharge.js / portOne.js에서 사용
=> 2024-11-05 정재준 pointController 수정

src/main/java/com/bungeobbang/app/view/memberController/MemberController.java
memberController에서 logout 페이지 이동 로직 남아있어서 삭제
=> 로그아웃 페이지 이동 로직 삭제

src/main/java/com/bungeobbang/app/view/pointController/PointController.java, src/main/webapp/WEB-INF/views/pointHistory.jsp
jsp / controller 페이지 수정
productName이 안나옴..
=> 포인트 사용내역 보기 수정 완료

src/main/java/com/bungeobbang/app/view/orderController/OrderController.java, src/main/resources/mappings/order-mapping.xml
OrderController 로직 추가 / insert 부분 가능
order-mapping.xml 반환값에 productName 추가하여 pointHistory.jsp에서 출력
=> 2024-11-05 정재준 Order Controller / order-mapping.xml 수정

src/main/java/com/bungeobbang/app/biz/advice/UserCheckAdvice.java, src/main/java/com/bungeobbang/app/biz/order/OrderDAO.java, src/main/java/com/bungeobbang/app/biz/order/OrderDTO.java, src/main/java/com/bungeobbang/app/view/memberController/AdminController.java, src/main/java/com/bungeobbang/app/view/memberController/MemberController.java, src/main/java/com/bungeobbang/app/view/memberController/MypageController.java, src/main/java/com/bungeobbang/app/view/util/SessionMemberPointUtil.java, src/main/resources/mappings/order-mapping.xml, src/main/webapp/WEB-INF/views/adminMainProduct.jsp
=> 관리자 주문 쪽 수정 및 포인트 갱신 유틸 적용

src/main/java/com/bungeobbang/app/view/paymentController/PaymentController.java, src/main/java/com/bungeobbang/app/view/paymentController/PortOneAPIController.java, src/main/java/com/bungeobbang/app/view/pointController/PointController.java, src/main/webapp/WEB-INF/views/productCart.jsp, src/main/webapp/resources/assets/js/point/portOne.js, src/main/webapp/resources/assets/js/product/productCart.js
prodcutCart.js에서 Point.do 요청값 변경
application에 포인트 저장 로직 session으로 변경
결제 완료되면 session에 저장된 포인트 받아서 history.back
=> 2024-11-06 정재준 controller 수정

src/main/webapp/WEB-INF/tags/boardSideBar.tag, src/main/webapp/WEB-INF/views/addressSearchStore.jsp, src/main/webapp/WEB-INF/views/boardList.jsp, src/main/webapp/WEB-INF/views/fixBoard.jsp, src/main/webapp/WEB-INF/views/moneyToPoint.jsp, src/main/webapp/WEB-INF/views/mypageUpdate.jsp, src/main/webapp/WEB-INF/views/pointHistory.jsp, src/main/webapp/WEB-INF/views/productCart.jsp, src/main/webapp/WEB-INF/views/productList.jsp, src/main/webapp/WEB-INF/views/store.jsp, src/main/webapp/WEB-INF/views/storeList.jsp
1. 장바구니
2. MD 상품 input css 수정
3. MD 상품 페지네이션 css 수정
4. MD 추천 상품 버튼 확인 (꾹 누르면 )
5. MD 내 포인트 보기 포인트 el식 변경
6. MD 1개짜리 검색이 안 됨 DAO
7. store.jsp 폐점 신고, 가게 삭제 js 오류
8. 인기글 내역이 나오는데 css로 구분
9. 댓글 삭제 안 됨
10. 좋아요 버튼이 없음
11. 게시글 수정 css 삭제 됨
12. 비공개 게시물 검증 추가(view), 본인, 관리자는 보여야 함
13. 가게 제보, 가게 등록 스윗 알랏 버튼이 3개
14. 가게 등록 후 성공하면 알랏(controller)
15. 결제 후 포인트 갱신(session)
16. 닉네임 중복 알림, 비밀번호, 중복 버튼 줄바꿈 없이
17. boardSidebar 버튼 경로
18. 회원가입 닉네임 중복검사 controller로 닉네임 값이 안 감
19. 회원탈퇴 페이지 이동으로 변경
20. 비밀번호 유효성 확인
21. 주문받은 상품 목록 여러 개 뜨는 것
22. 비밀번호 찾기에 비밀번호 변경이 안 됨
23. 구매 안 됨
=> 20241106 전체 코드 확인

src/main/java/com/bungeobbang/app/biz/product/ProductDAO.java, src/main/webapp/WEB-INF/views/productCart.jsp, src/main/webapp/WEB-INF/views/productList.jsp, src/main/webapp/resources/assets/css/product/productCart.css, src/main/webapp/resources/assets/js/member/signUp.js, src/main/webapp/resources/assets/js/product/productCart.js, src/main/webapp/resources/assets/js/product/productList.js
1. 장바구니
2. MD 상품 input css 수정
5. MD 내 포인트 보기 포인트 el식 변경
6. MD 1개짜리 검색이 안 됨 DAO
0. 비밀번호 유효성 확인
=> 20241106 안제호 마이페이지 업데이트 부분 로직 수정 #147

src/main/webapp/resources/assets/js/board/board.js
=> 2024.11.06 정재희 board.js do명 변경

src/main/webapp/signUp.jsp
=> 141 20241106 signUp.jsp 

src/main/webapp/resources/assets/js/member/signUp.js, src/main/webapp/signUp.jsp
=> 회원가입 에러 핸들링

src/main/java/com/bungeobbang/app/view/paymentController/PaymentController.java, src/main/java/com/bungeobbang/app/view/paymentController/PortOneAPIController.java, src/main/java/com/bungeobbang/app/view/pointController/PointController.java, src/main/webapp/WEB-INF/views/moneyToPoint.jsp, src/main/webapp/WEB-INF/views/pointRecharge.jsp, src/main/webapp/resources/assets/js/point/pointRecharge.js, src/main/webapp/resources/assets/js/point/portOne.js
point payment 관련 session저장 포인트 불러오기 수정 및 충전페이지 포인트 보여주는 로직 수정
=> point payment 수정

src/main/webapp/WEB-INF/tags/footer.tag, src/main/webapp/resources/assets/css/footer.css
footer.tag
- margin 없앰
- 내용 변경
=> 2024.11.07 정재희 footer.tag 수정

src/main/java/com/bungeobbang/app/biz/payment/PaymentTokenService.java, src/main/webapp/resources/assets/js/point/pointRecharge.js, src/main/webapp/resources/assets/js/point/portOne.js
결제 API 키 값 삭제
PaymentTokenService.java 토큰 발급 값 삭제
pointRecharge.js 채널 키 값 삭제
portOne.sj imp 값 삭제
=> 2024-11-07 API 키 값 삭제

src/main/resources/application.properties, src/main/webapp/resources/assets/css/product/productList.css, src/main/webapp/resources/assets/js/product/productCart.js, src/main/webapp/resources/assets/js/product/productList.js
1. 이메일 /비밀번호 제거
2.상품쪽 최종 에러 체크
=> 20241107 최종 수정

src/main/webapp/WEB-INF/views/main.jsp, src/main/webapp/resources/assets/css/mainPage.css
=> main 팀소개 추가

src/main/webapp/WEB-INF/views/productList.jsp
=> 안제호 productList.jsp 

src/main/webapp/WEB-INF/tags/adminfooter.tag, src/main/webapp/WEB-INF/views/adminMainProduct.jsp, src/main/webapp/WEB-INF/views/adminStoreRegister.jsp, src/main/webapp/WEB-INF/views/closedStoreDeclareList.jsp, src/main/webapp/WEB-INF/views/storeDeclareList.jsp
관리자페이지 수정
1. 태그화(사이드바, 하단)
2. 가게 등록 페이지 토글 문제 해결(js 추가)
3. 하단 파비콘 부분 출력 문제 해결
=> 11/7 11:20 고미진 관리자페이지 메뉴 토글 및 하단 수정

src/main/java/com/bungeobbang/app/view/orderController/OrderController.java
orderController에서 포인트 갱신해주는 거 추가
=> orderController 포인트 갱신 추가

src/main/webapp/WEB-INF/tags/header.tag, src/main/webapp/WEB-INF/views/productCart.jsp, src/main/webapp/WEB-INF/views/productList.jsp, src/main/webapp/resources/assets/css/product/productCart.css, src/main/webapp/resources/assets/css/product/productList.css, src/main/webapp/resources/assets/js/daumPostCode2.js, src/main/webapp/resources/assets/js/header.js, src/main/webapp/resources/assets/js/product/productList.js
1. Header
2. 주문 daumPostCode API
3. 기타 CSS 마지막체크
=> 20241108 제출 직전 오류 수정

src/main/webapp/resources/assets/js/store/storeList.js
storeList.js
- 운영 상태 태그도 유지하도록 코드 추가
=> 2024.11.08 가게 필터 검색 운영상태 태그 유지 추가

src/main/java/com/bungeobbang/app/biz/payment/PaymentDAO.java
paymentDTO selectAll 한개로 수정 -> 관리자에서는 사용하지 않음
=> 2024-11-08 정재준 paymentDAO 수정

src/main/webapp/WEB-INF/tags/header.tag
=> header.tag 가게 제보 링크 수정

src/main/java/com/bungeobbang/app/biz/store/StoreDAO.java, src/main/java/com/bungeobbang/app/view/storeController/StoreAsyncController.java
=> 주소 검색 갯수 늘림

src/main/webapp/WEB-INF/views/adminMainProduct.jsp, src/main/webapp/WEB-INF/views/adminStoreRegister.jsp, src/main/webapp/WEB-INF/views/closedStoreDeclareList.jsp, src/main/webapp/WEB-INF/views/myBoardList.jsp, src/main/webapp/WEB-INF/views/mypageUpdate.jsp, src/main/webapp/WEB-INF/views/signOut.jsp, src/main/webapp/login.jsp, src/main/webapp/resources/assets/js/closedStoreDeclareList.js, src/main/webapp/resources/assets/js/member/loginPwFind.js, src/main/webapp/resources/assets/js/member/mypageUpdate.js, src/main/webapp/resources/assets/js/member/resetPw.js, src/main/webapp/resources/assets/js/member/sendEmail.js, src/main/webapp/resources/assets/js/member/signUp.js, src/main/webapp/resources/assets/js/storeDeclareList.js, src/main/webapp/signUp.jsp
=> 11/8 12:30 기능 최종점검 및 주석 정리(회원, 관리자페이지)
